use serde::de::DeserializeOwned;
use tauri::{
    plugin::{PluginApi, PluginHandle},
    AppHandle, Runtime,
};

use crate::models::*;

#[cfg(target_os = "ios")]
tauri::ios_plugin_binding!(init_plugin_sharetarget);

/// Access to the sharetarget APIs.
pub struct ShareTarget<R: Runtime>(PluginHandle<R>);

///  ShareTarget methods. Note that `ShareTarget::registerListener()` will be autogenerated.
impl<R: Runtime> ShareTarget<R> {
    /// A simple ping function. Just lets you know the plugin is still alive.
    pub fn ping(&self, payload: PingRequest) -> crate::Result<PingResponse> {
        self
            .0
            .run_mobile_plugin("ping", payload)
            .map_err(Into::into)
    }
}

/// Initialize the Kotlin class attached to this plugin.
pub fn init<R: Runtime, C: DeserializeOwned>(
    _app: &AppHandle<R>,
    _api: PluginApi<R, C>,
) -> crate::Result<ShareTarget<R>> {
    let handle = _api.register_android_plugin("app.tauri.sharetarget", "ShareTargetPlugin")?;

    Ok(ShareTarget(handle))
}

